export const formatOptions = {
    image: [
      { value: "", label: "..." },
      { value: "jpg", label: "JPG" },
      { value: "jpeg", label: "JPEG" },
      { value: "png", label: "PNG" },
      { value: "webp", label: "WEBP" },
      { value: "bmp", label: "BMP" },
      { value: "tiff", label: "TIFF" },
      { value: "avif", label: "AVIF" },
      { value: "gif", label: "GIF" },
    ],
    video: [
      { value: "", label: "..." },
      { value: "mp4", label: "MP4" },
      { value: "avi", label: "AVI" },
      { value: "mov", label: "MOV" },
      { value: "webm", label: "WEBM" },
      { value: "wmv", label: "WMV" },
      { value: "mkv", label: "MKV" },
    ],
    audio: [
      { value: "", label: "..." },
      { value: "mp3", label: "MP3" },
      { value: "aac", label: "AAC" },
      { value: "flac", label: "FLAC" },
      { value: "ogg", label: "OGG" },
      { value: "wav", label: "WAV" },
      { value: "m4a", label: "M4A" },
    ],
    // document: [
    //   { value: "", label: "..." },
    //   { value: "pdf", label: "PDF" },
    //   { value: "docx", label: "DOCX" },
    //   { value: "txt", label: "TXT" },
    //   { value: "rtf", label: "RTF" },
    //   { value: "md", label: "MD" },
    //   { value: "json", label: "JSON" },
    // ],
  };